# Generated by Django 3.1.5 on 2021-02-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=150)),
                ('about_image1', models.ImageField(upload_to='about')),
                ('about_image2', models.ImageField(upload_to='about')),
                ('population', models.IntegerField()),
                ('properties', models.IntegerField()),
                ('average_house', models.IntegerField()),
                ('branches', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('properties', models.IntegerField()),
                ('agent_image', models.ImageField(upload_to='agent_rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('number', models.IntegerField()),
                ('text', models.TextField(max_length=50)),
                ('blog_image', models.ImageField(upload_to='blog_rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('specialist', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='client')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('nav_image', models.ImageField(upload_to='body_rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.region')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('price', models.CharField(choices=[('5000', '5000'), ('10000', '10000'), ('500000', '500000'), ('1000000', '1000000'), ('2000000', '2000000'), ('3000000', '3000000'), ('4000000', '4000000'), ('5000000', '5000000'), ('6000000', '6000000'), ('7000000', '7000000'), ('8000000', '8000000'), ('9000000', '9000000'), ('10000000', '10000000'), ('20000000', '20000000')], max_length=50)),
                ('person_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.region')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.status')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecover.type')),
                ('view', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ecover.view')),
            ],
        ),
    ]
