# Generated by Django 3.1.5 on 2021-01-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('properties', models.IntegerField()),
                ('image', models.ImageField(upload_to='agent_rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('number', models.IntegerField()),
                ('text', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('addres', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('views', models.TextField(max_length=60)),
                ('image', models.ImageField(upload_to='picture')),
                ('image_person', models.ImageField(upload_to='image_person')),
                ('person_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.region')),
            ],
        ),
    ]
