# Generated by Django 3.1.4 on 2021-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.TextField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
