# Generated by Django 3.1.5 on 2021-01-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecover.region'),
            preserve_default=False,
        ),
    ]
