# Generated by Django 3.1.5 on 2021-01-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blog_rasm'),
            preserve_default=False,
        ),
    ]
