# Generated by Django 3.1.5 on 2021-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0002_remove_announcement_image_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, upload_to='picture'),
        ),
    ]
