# Generated by Django 3.1.5 on 2021-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0002_district_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=models.TextField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
