# Generated by Django 3.1.5 on 2021-03-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0002_announcement_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecover.agent'),
        ),
    ]
