# Generated by Django 3.1.5 on 2021-03-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0003_announcement_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='average_house',
        ),
        migrations.RemoveField(
            model_name='about',
            name='population',
        ),
        migrations.RemoveField(
            model_name='about',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='properties',
        ),
    ]
