# Generated by Django 3.1.5 on 2021-02-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0003_auto_20210208_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='image',
            new_name='agent_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='blog_image',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
