# Generated by Django 3.1.5 on 2021-02-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0003_auto_20210222_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='phone',
            field=models.CharField(default='+', max_length=20),
        ),
    ]
