# Generated by Django 3.1.5 on 2021-03-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0004_auto_20210224_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_city', models.ImageField(upload_to='city_image')),
                ('properties', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.region')),
            ],
        ),
    ]
