# Generated by Django 3.1.5 on 2021-02-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecover', '0004_auto_20210212_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
