# Generated by Django 3.1.5 on 2021-03-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0004_auto_20210305_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecover.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
