# Generated by Django 3.1.5 on 2021-02-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0005_auto_20210215_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='person_name',
            field=models.CharField(max_length=20),
        ),
    ]
