# Generated by Django 3.1.5 on 2021-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0005_auto_20210306_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author_image',
            field=models.ImageField(default='', upload_to='author_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
