# Generated by Django 3.1.5 on 2021-03-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0006_auto_20210303_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(upload_to='region_image'),
        ),
    ]
