# Generated by Django 3.1.5 on 2021-03-07 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecover', '0006_auto_20210306_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='phone',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecover.type'),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image', models.ImageField(upload_to='author_image')),
                ('phone', models.CharField(default='+998', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
