# Generated by Django 3.1.5 on 2021-03-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0007_auto_20210307_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
