# Generated by Django 3.1.5 on 2021-03-04 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecover', '0007_auto_20210303_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='person_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
