# Generated by Django 3.1.5 on 2021-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0008_delete_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
