# Generated by Django 3.1.5 on 2021-03-08 12:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0009_auto_20210308_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 8, 17, 42, 53, 338153)),
        ),
    ]
