# Generated by Django 3.1.5 on 2021-03-14 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0010_auto_20210308_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecover.agent'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone',
            field=models.CharField(blank=True, default='+998', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 14, 11, 12, 49, 170632)),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
