# Generated by Django 3.1.5 on 2021-03-15 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0013_auto_20210315_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 15, 19, 43, 40, 315447)),
        ),
    ]
