# Generated by Django 3.1.5 on 2021-03-15 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0015_auto_20210315_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 15, 19, 57, 19, 977400)),
        ),
    ]
