# Generated by Django 3.1.5 on 2021-03-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0016_auto_20210315_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
