# Generated by Django 3.1.5 on 2021-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecover', '0017_auto_20210316_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
