# Generated by Django 3.1.5 on 2021-03-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
