# Generated by Django 3.1.5 on 2021-03-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0002_auto_20210317_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
