# Generated by Django 3.1.5 on 2021-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210308_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='author_image',
            field=models.ImageField(blank=True, default='author.jpg', null=True, upload_to='author_image'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, default='+998', max_length=20, null=True),
        ),
    ]
