# Generated by Django 3.1.5 on 2021-03-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecover', '0012_auto_20210315_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('blog_image', models.ImageField(upload_to='blog_rasm')),
                ('content_header', models.CharField(max_length=1000)),
                ('blog_single_image', models.ImageField(upload_to='blog_rasm')),
                ('content_body', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecover.agent')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_categories')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.type')),
            ],
        ),
    ]
