# Generated by Django 3.1.5 on 2021-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='paragraph',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
