# Generated by Django 3.1.5 on 2021-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210315_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_single_image',
            new_name='blog_single_image1',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_single_image2',
            field=models.ImageField(default='', upload_to='blog_rasm'),
            preserve_default=False,
        ),
    ]
